Input string: Output string: minus dziewięćset dziewięćdziesiąt dziewięć i dziewięćset dziewięćdziesiąt dziewięć tysięcznych
Input string: Output string: dziewięćset dziewięćdziesiąt dziewięć i dziewięćset dziewięćdziesiąt jeden tysięcznych
Input string: Output string: trzy i jedna dziesiąta
Input string: Output string: dwanaście i sześćdziesiąt siedem setnych
Input string: Output string: minus trzydzieści
Input string: Output string: minus trzydzieści pięć i sto dwadzieścia jeden tysięcznych
Input string: Output string: jedna dziesiąta
Input string: Output string: jedna setna
Input string: Output string: jedna tysięczna
Input string: Output string: zero
Input string: Output string: osiem i jedna setna
Input string: Output string: osiem i pięć setnych
Input string: 